export const FETCH_NUMBERS_SUCCESS ="FETCH_NUMBERS_SUCCESS";
export const FETCH_NUMBERS_FAILERE ="FETCH_NUMBERS_FAILERE";
export const SELECT_NUMBERS_SUCCESS ="SELECT_NUMBERS_SUCCESS";
export const SELECT_NUMBERS_FAILERE ="SELECT_NUMBERS_FAILERE";